name: Pipeline

on:
  pull_request:
    types: [closed]
    paths:
      - "datasets/**"
      - "support/**"
  workflow_dispatch:
    inputs:
      dataset:
        description: "Path config (es. datasets/laureati/dataset.yml o support/anagrafica-atenei/dataset.yml)"
        required: false
        default: ""

jobs:
  pipeline:
    if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
    uses: dataciviclab/.github/.github/workflows/pipeline-reusable.yml@main
    with:
      repo-slug: "open_mur"
      run-command: ${{ inputs.dataset == '' && 'make run-all' || format('toolkit run --config {0}', inputs.dataset) }}
      extra-env: "BLOCKED_SOURCE_PROXY=${{ vars.BLOCKED_SOURCE_PROXY }}"
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
